<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260625153342 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE absence (id INT AUTO_INCREMENT NOT NULL, student_id INT NOT NULL, absence_type_id INT NOT NULL, recorded_by_id INT DEFAULT NULL, justified_by_id INT DEFAULT NULL, school_id INT NOT NULL, period_id INT DEFAULT NULL, date DATE NOT NULL, start_time TIME DEFAULT NULL, end_time TIME DEFAULT NULL, reason LONGTEXT DEFAULT NULL, justification LONGTEXT DEFAULT NULL, justification_status VARCHAR(50) DEFAULT NULL, justification_document VARCHAR(255) DEFAULT NULL, justification_date DATETIME DEFAULT NULL, justification_submitted_at DATETIME DEFAULT NULL, notes LONGTEXT DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_765AE0C9CB944F1A (student_id), INDEX IDX_765AE0C9CCAA91B (absence_type_id), INDEX IDX_765AE0C9D05A957B (recorded_by_id), INDEX IDX_765AE0C9CD130C9C (justified_by_id), INDEX IDX_765AE0C9C32A47EE (school_id), INDEX IDX_765AE0C9EC8B7ADE (period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE absence_type (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, code VARCHAR(20) NOT NULL, type VARCHAR(20) NOT NULL, requires_justification TINYINT(1) NOT NULL, counts_as_absence TINYINT(1) NOT NULL, penalty_points NUMERIC(5, 2) DEFAULT NULL, color VARCHAR(7) DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_FBCF99B6C32A47EE (school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bulletin (id INT AUTO_INCREMENT NOT NULL, level_id INT NOT NULL, period_id INT NOT NULL, school_id INT NOT NULL, school_year_id INT NOT NULL, created_by_id INT DEFAULT NULL, validated_by_id INT DEFAULT NULL, libelle VARCHAR(150) NOT NULL, moyenne_sur INT NOT NULL, created_at DATETIME NOT NULL, is_validated TINYINT(1) DEFAULT 0 NOT NULL, validated_at DATETIME DEFAULT NULL, computed_at DATETIME DEFAULT NULL, INDEX IDX_2B7D89425FB14BA7 (level_id), INDEX IDX_2B7D8942EC8B7ADE (period_id), INDEX IDX_2B7D8942C32A47EE (school_id), INDEX IDX_2B7D8942D2EECC3F (school_year_id), INDEX IDX_2B7D8942B03A8386 (created_by_id), INDEX IDX_2B7D8942C69DE5E5 (validated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bulletin_line (id INT AUTO_INCREMENT NOT NULL, bulletin_id INT NOT NULL, student_id INT NOT NULL, average NUMERIC(6, 2) DEFAULT NULL, rang INT DEFAULT NULL, mention VARCHAR(60) DEFAULT NULL, INDEX IDX_140A301FD1AAB236 (bulletin_id), INDEX IDX_140A301FCB944F1A (student_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cash_deposit (id INT AUTO_INCREMENT NOT NULL, cash_register_id INT NOT NULL, recorded_by_id INT DEFAULT NULL, approved_by_id INT DEFAULT NULL, reference VARCHAR(100) NOT NULL, amount NUMERIC(12, 2) NOT NULL, deposit_date DATETIME NOT NULL, notes LONGTEXT DEFAULT NULL, status VARCHAR(20) DEFAULT \'en_attente\' NOT NULL, approved_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_CB378F65A917CC69 (cash_register_id), INDEX IDX_CB378F65D05A957B (recorded_by_id), INDEX IDX_CB378F652D234F6A (approved_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cash_register (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, cashier_id INT DEFAULT NULL, validated_by_id INT DEFAULT NULL, authorized_by_id INT DEFAULT NULL, is_online TINYINT(1) DEFAULT 0 NOT NULL, status VARCHAR(20) NOT NULL, opening_balance NUMERIC(10, 2) NOT NULL, closing_balance NUMERIC(10, 2) DEFAULT NULL, opened_at DATETIME NOT NULL, closed_at DATETIME DEFAULT NULL, is_validated TINYINT(1) DEFAULT 0 NOT NULL, validated_at DATETIME DEFAULT NULL, expense_authorized TINYINT(1) DEFAULT 0 NOT NULL, authorized_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_3D7AB1D9C32A47EE (school_id), INDEX IDX_3D7AB1D92EDB0489 (cashier_id), INDEX IDX_3D7AB1D9C69DE5E5 (validated_by_id), INDEX IDX_3D7AB1D92B62D3A1 (authorized_by_id), INDEX idx_cash_register_status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classroom (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, school_year_id INT NOT NULL, level_id INT NOT NULL, faculty_id INT DEFAULT NULL, round_id INT DEFAULT NULL, main_teacher_id INT DEFAULT NULL, room_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(50) NOT NULL, capacity INT DEFAULT NULL, description LONGTEXT DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_497D309D77153098 (code), INDEX IDX_497D309DC32A47EE (school_id), INDEX IDX_497D309DD2EECC3F (school_year_id), INDEX IDX_497D309D5FB14BA7 (level_id), INDEX IDX_497D309D680CAB68 (faculty_id), INDEX IDX_497D309DA6005CA0 (round_id), INDEX IDX_497D309D79780A7E (main_teacher_id), INDEX IDX_497D309D54177093 (room_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contract (id INT AUTO_INCREMENT NOT NULL, employee_id INT NOT NULL, reference VARCHAR(50) NOT NULL, contract_type VARCHAR(30) NOT NULL, job_title VARCHAR(255) DEFAULT NULL, start_date DATE NOT NULL, end_date DATE DEFAULT NULL, trial_end_date DATE DEFAULT NULL, base_salary NUMERIC(12, 2) DEFAULT NULL, weekly_hours NUMERIC(5, 2) DEFAULT NULL, status VARCHAR(20) NOT NULL, notes LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_E98F2859AEA34913 (reference), INDEX IDX_E98F28598C03F15C (employee_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE course (id INT AUTO_INCREMENT NOT NULL, classroom_id INT NOT NULL, subject_id INT NOT NULL, teacher_id INT DEFAULT NULL, time_slot_id INT NOT NULL, room_id INT DEFAULT NULL, day_of_week VARCHAR(20) NOT NULL, notes LONGTEXT DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_169E6FB96278D5A8 (classroom_id), INDEX IDX_169E6FB923EDC87 (subject_id), INDEX IDX_169E6FB941807E1D (teacher_id), INDEX IDX_169E6FB9D62B0FA (time_slot_id), INDEX IDX_169E6FB954177093 (room_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cycle (id INT AUTO_INCREMENT NOT NULL, school_id INT DEFAULT NULL, libelle VARCHAR(100) NOT NULL, INDEX IDX_B086D193C32A47EE (school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE depense (id INT AUTO_INCREMENT NOT NULL, cash_register_id INT NOT NULL, school_id INT DEFAULT NULL, recorded_by_id INT DEFAULT NULL, numero VARCHAR(50) NOT NULL, libelle VARCHAR(150) NOT NULL, category VARCHAR(20) NOT NULL, amount NUMERIC(12, 2) NOT NULL, depense_date DATE NOT NULL, payment_method VARCHAR(20) NOT NULL, beneficiary VARCHAR(150) DEFAULT NULL, reference VARCHAR(100) DEFAULT NULL, description LONGTEXT DEFAULT NULL, notes LONGTEXT DEFAULT NULL, status VARCHAR(20) DEFAULT \'confirmée\' NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_34059757F55AE19E (numero), INDEX IDX_34059757A917CC69 (cash_register_id), INDEX IDX_34059757C32A47EE (school_id), INDEX IDX_34059757D05A957B (recorded_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, is_required TINYINT(1) NOT NULL, is_active TINYINT(1) NOT NULL, allowed_mime_types JSON NOT NULL, max_file_size INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE employee (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(20) DEFAULT NULL, address LONGTEXT DEFAULT NULL, date_of_birth DATE DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, employee_type VARCHAR(50) NOT NULL, position VARCHAR(255) DEFAULT NULL, department VARCHAR(255) DEFAULT NULL, salary NUMERIC(10, 2) DEFAULT NULL, hire_date DATE DEFAULT NULL, termination_date DATE DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_5D9F75A1A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE employee_school (employee_id INT NOT NULL, school_id INT NOT NULL, INDEX IDX_D0AF1E2E8C03F15C (employee_id), INDEX IDX_D0AF1E2EC32A47EE (school_id), PRIMARY KEY(employee_id, school_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE evaluation (id INT AUTO_INCREMENT NOT NULL, classroom_id INT NOT NULL, subject_id INT NOT NULL, period_id INT NOT NULL, teacher_id INT DEFAULT NULL, name VARCHAR(150) NOT NULL, type VARCHAR(50) NOT NULL, date DATE NOT NULL, max_grade NUMERIC(5, 2) NOT NULL, coefficient NUMERIC(5, 2) NOT NULL, description LONGTEXT DEFAULT NULL, is_published TINYINT(1) NOT NULL, is_active TINYINT(1) NOT NULL, is_validated TINYINT(1) DEFAULT 0 NOT NULL, locked_by_bulletin TINYINT(1) DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_1323A5756278D5A8 (classroom_id), INDEX IDX_1323A57523EDC87 (subject_id), INDEX IDX_1323A575EC8B7ADE (period_id), INDEX IDX_1323A57541807E1D (teacher_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE faculty (id INT AUTO_INCREMENT NOT NULL, cycle_id INT NOT NULL, school_id INT DEFAULT NULL, libelle VARCHAR(100) NOT NULL, INDEX IDX_179660435EC1162 (cycle_id), INDEX IDX_17966043C32A47EE (school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fee (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, level_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(50) NOT NULL, amount NUMERIC(10, 2) NOT NULL, description LONGTEXT DEFAULT NULL, type VARCHAR(20) NOT NULL, category VARCHAR(20) NOT NULL, frequency VARCHAR(20) NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_964964B577153098 (code), INDEX IDX_964964B5C32A47EE (school_id), INDEX IDX_964964B55FB14BA7 (level_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fee_schedule (id INT AUTO_INCREMENT NOT NULL, fee_id INT NOT NULL, order_number INT NOT NULL, amount NUMERIC(10, 2) NOT NULL, due_date DATE NOT NULL, INDEX IDX_3806BAFCAB45AECA (fee_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `grade` (id INT AUTO_INCREMENT NOT NULL, evaluation_id INT NOT NULL, student_id INT NOT NULL, entered_by_id INT DEFAULT NULL, value NUMERIC(5, 2) DEFAULT NULL, status VARCHAR(20) DEFAULT NULL, comment LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_595AAE34456C5646 (evaluation_id), INDEX IDX_595AAE34CB944F1A (student_id), INDEX IDX_595AAE34C443EDD (entered_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE level (id INT AUTO_INCREMENT NOT NULL, school_id INT DEFAULT NULL, cycle_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, order_number INT NOT NULL, description LONGTEXT DEFAULT NULL, is_active TINYINT(1) NOT NULL, INDEX IDX_9AEACC13C32A47EE (school_id), INDEX IDX_9AEACC135EC1162 (cycle_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mobile_money_config (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, provider VARCHAR(30) NOT NULL, base_url VARCHAR(255) DEFAULT NULL, api_key VARCHAR(255) DEFAULT NULL, api_secret VARCHAR(255) DEFAULT NULL, webhook_secret VARCHAR(255) DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_5A7666C9C32A47EE (school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, recipient_id INT NOT NULL, title VARCHAR(255) NOT NULL, message LONGTEXT NOT NULL, icon VARCHAR(50) DEFAULT NULL, link VARCHAR(255) DEFAULT NULL, is_read TINYINT(1) DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_BF5476CAE92F8F78 (recipient_id), INDEX idx_notification_recipient_read (recipient_id, is_read), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment (id INT AUTO_INCREMENT NOT NULL, student_id INT NOT NULL, fee_id INT NOT NULL, student_fee_id INT DEFAULT NULL, recorded_by_id INT DEFAULT NULL, cash_register_id INT DEFAULT NULL, payment_number VARCHAR(50) NOT NULL, amount NUMERIC(10, 2) NOT NULL, payment_date DATE NOT NULL, payment_method VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, notes LONGTEXT DEFAULT NULL, reference VARCHAR(100) DEFAULT NULL, receipt_path VARCHAR(255) DEFAULT NULL, provider VARCHAR(30) DEFAULT NULL, provider_transaction_id VARCHAR(100) DEFAULT NULL, provider_status VARCHAR(40) DEFAULT NULL, payer_phone VARCHAR(30) DEFAULT NULL, checkout_url LONGTEXT DEFAULT NULL, idempotency_key VARCHAR(64) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_6D28840DB3A884C2 (payment_number), UNIQUE INDEX UNIQ_6D28840D771D04A7 (provider_transaction_id), UNIQUE INDEX UNIQ_6D28840D7FD1C147 (idempotency_key), INDEX IDX_6D28840DCB944F1A (student_id), INDEX IDX_6D28840DAB45AECA (fee_id), INDEX IDX_6D28840D2573764A (student_fee_id), INDEX IDX_6D28840DD05A957B (recorded_by_id), INDEX IDX_6D28840DA917CC69 (cash_register_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment_webhook_event (id INT AUTO_INCREMENT NOT NULL, provider VARCHAR(30) NOT NULL, event_id VARCHAR(100) NOT NULL, type VARCHAR(50) DEFAULT NULL, payload LONGTEXT DEFAULT NULL, signature_valid TINYINT(1) NOT NULL, received_at DATETIME NOT NULL, processed_at DATETIME DEFAULT NULL, UNIQUE INDEX uniq_provider_event (provider, event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE period (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, school_year_id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(50) NOT NULL, order_number INT NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_C5B81ECEC32A47EE (school_id), INDEX IDX_C5B81ECED2EECC3F (school_year_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pre_registration (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, requested_level_id INT DEFAULT NULL, school_year_id INT DEFAULT NULL, validated_by_id INT DEFAULT NULL, submitted_by_id INT DEFAULT NULL, existing_student_id INT DEFAULT NULL, matricule_interne VARCHAR(50) DEFAULT NULL, matricule_national VARCHAR(50) DEFAULT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, date_of_birth DATE NOT NULL, gender VARCHAR(1) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, address LONGTEXT DEFAULT NULL, place_of_birth VARCHAR(255) DEFAULT NULL, nationality VARCHAR(100) DEFAULT NULL, birth_certificate_number VARCHAR(100) DEFAULT NULL, cmu_number VARCHAR(50) DEFAULT NULL, last_school_attended VARCHAR(255) DEFAULT NULL, is_repeating TINYINT(1) DEFAULT 0 NOT NULL, photo VARCHAR(255) DEFAULT NULL, parent_name VARCHAR(255) DEFAULT NULL, parent_phone VARCHAR(20) DEFAULT NULL, parent_email VARCHAR(255) DEFAULT NULL, parent_function VARCHAR(255) DEFAULT NULL, parent_address LONGTEXT DEFAULT NULL, emergency_contact VARCHAR(255) DEFAULT NULL, emergency_phone VARCHAR(20) DEFAULT NULL, medical_info VARCHAR(255) DEFAULT NULL, notes LONGTEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, type VARCHAR(20) DEFAULT \'new\' NOT NULL, rejection_reason LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, validated_at DATETIME DEFAULT NULL, enrolled_at DATETIME DEFAULT NULL, INDEX IDX_A2FEF1B9C32A47EE (school_id), INDEX IDX_A2FEF1B92EC20237 (requested_level_id), INDEX IDX_A2FEF1B9D2EECC3F (school_year_id), INDEX IDX_A2FEF1B9C69DE5E5 (validated_by_id), INDEX IDX_A2FEF1B979F7D87D (submitted_by_id), INDEX IDX_A2FEF1B970E6A2D4 (existing_student_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pre_registration_document (id INT AUTO_INCREMENT NOT NULL, pre_registration_id INT NOT NULL, document_type_id INT DEFAULT NULL, validated_by_id INT DEFAULT NULL, file_name VARCHAR(255) NOT NULL, original_file_name VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, file_size INT NOT NULL, file_path VARCHAR(500) NOT NULL, description LONGTEXT DEFAULT NULL, is_validated TINYINT(1) NOT NULL, validation_notes LONGTEXT DEFAULT NULL, uploaded_at DATETIME NOT NULL, validated_at DATETIME DEFAULT NULL, INDEX IDX_413A5C65FB6C0FEA (pre_registration_id), INDEX IDX_413A5C6561232A4F (document_type_id), INDEX IDX_413A5C65C69DE5E5 (validated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE registration (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, school_year_id INT NOT NULL, classroom_id INT DEFAULT NULL, pre_registration_id INT DEFAULT NULL, is_repeating TINYINT(1) NOT NULL, boursier TINYINT(1) NOT NULL, is_active TINYINT(1) NOT NULL, enrolled_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_62A8A7A7C32A47EE (school_id), INDEX IDX_62A8A7A7D2EECC3F (school_year_id), INDEX IDX_62A8A7A76278D5A8 (classroom_id), UNIQUE INDEX UNIQ_62A8A7A7FB6C0FEA (pre_registration_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE room (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(50) NOT NULL, capacity INT DEFAULT NULL, type VARCHAR(50) DEFAULT NULL, floor VARCHAR(50) DEFAULT NULL, building VARCHAR(50) DEFAULT NULL, equipment LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_729F519BC32A47EE (school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE round (id INT AUTO_INCREMENT NOT NULL, cycle_id INT NOT NULL, school_id INT DEFAULT NULL, libelle VARCHAR(100) NOT NULL, INDEX IDX_C5EEEA345EC1162 (cycle_id), INDEX IDX_C5EEEA34C32A47EE (school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school (id INT AUTO_INCREMENT NOT NULL, school_group_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(50) NOT NULL, type VARCHAR(50) NOT NULL, address LONGTEXT DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, director VARCHAR(100) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, cachet_direction VARCHAR(255) DEFAULT NULL, badge_background_color VARCHAR(20) DEFAULT NULL, sous_tutelle VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, is_active TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_F99EDABB77153098 (code), INDEX IDX_F99EDABB12ED03 (school_group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_B33AF2DF77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_year (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, is_current TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE student (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, parent_user_id INT DEFAULT NULL, pre_registration_id INT DEFAULT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, address LONGTEXT DEFAULT NULL, date_of_birth DATE DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, matricule_interne VARCHAR(50) DEFAULT NULL, matricule_national VARCHAR(50) DEFAULT NULL, place_of_birth VARCHAR(255) DEFAULT NULL, nationality VARCHAR(100) DEFAULT NULL, birth_certificate_number VARCHAR(100) DEFAULT NULL, cmu_number VARCHAR(50) DEFAULT NULL, last_school_attended VARCHAR(255) DEFAULT NULL, photo VARCHAR(255) DEFAULT NULL, parent_name VARCHAR(255) DEFAULT NULL, parent_phone VARCHAR(20) DEFAULT NULL, parent_email VARCHAR(255) DEFAULT NULL, parent_function VARCHAR(255) DEFAULT NULL, parent_address LONGTEXT DEFAULT NULL, emergency_contact VARCHAR(255) DEFAULT NULL, emergency_phone VARCHAR(20) DEFAULT NULL, medical_info VARCHAR(255) DEFAULT NULL, notes LONGTEXT DEFAULT NULL, is_active TINYINT(1) NOT NULL, status VARCHAR(20) DEFAULT \'non_affecte\' NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_B723AF33C32A47EE (school_id), INDEX IDX_B723AF33D526A7D3 (parent_user_id), UNIQUE INDEX UNIQ_B723AF33FB6C0FEA (pre_registration_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE student_dropout (id INT AUTO_INCREMENT NOT NULL, student_id INT NOT NULL, recorded_by_id INT DEFAULT NULL, validated_by_id INT DEFAULT NULL, reason LONGTEXT NOT NULL, dropout_date DATE NOT NULL, status VARCHAR(20) DEFAULT \'enregistré\' NOT NULL, validated_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_7FBF5A31CB944F1A (student_id), INDEX IDX_7FBF5A31D05A957B (recorded_by_id), INDEX IDX_7FBF5A31C69DE5E5 (validated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE student_fee (id INT AUTO_INCREMENT NOT NULL, student_id INT NOT NULL, fee_id INT NOT NULL, registration_id INT DEFAULT NULL, amount NUMERIC(10, 2) NOT NULL, paid_amount NUMERIC(10, 2) NOT NULL, status VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_346113CB944F1A (student_id), INDEX IDX_346113AB45AECA (fee_id), INDEX IDX_346113833D8F43 (registration_id), UNIQUE INDEX unique_student_fee (student_id, fee_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE student_transfer (id INT AUTO_INCREMENT NOT NULL, student_id INT NOT NULL, from_classroom_id INT DEFAULT NULL, to_classroom_id INT NOT NULL, school_year_id INT DEFAULT NULL, recorded_by_id INT DEFAULT NULL, motif LONGTEXT NOT NULL, document_path VARCHAR(500) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_F3BFEF5BCB944F1A (student_id), INDEX IDX_F3BFEF5B5F3E0F4E (from_classroom_id), INDEX IDX_F3BFEF5BB6ED7674 (to_classroom_id), INDEX IDX_F3BFEF5BD2EECC3F (school_year_id), INDEX IDX_F3BFEF5BD05A957B (recorded_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subject (id INT AUTO_INCREMENT NOT NULL, school_id INT DEFAULT NULL, level_id INT DEFAULT NULL, type_id INT DEFAULT NULL, subject_equivalent_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(50) NOT NULL, coefficient NUMERIC(5, 2) DEFAULT NULL, description LONGTEXT DEFAULT NULL, hours_per_week INT DEFAULT NULL, bulletin_order_number INT DEFAULT NULL, color VARCHAR(7) DEFAULT NULL, lv VARCHAR(20) DEFAULT \'AUCUN\', matiere_conduite VARCHAR(5) DEFAULT NULL, art_musique VARCHAR(20) DEFAULT NULL, note_sur_bulletin INT DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_FBCE3E7A77153098 (code), INDEX IDX_FBCE3E7AC32A47EE (school_id), INDEX IDX_FBCE3E7A5FB14BA7 (level_id), INDEX IDX_FBCE3E7AC54C8C93 (type_id), INDEX IDX_FBCE3E7AA8A850D1 (subject_equivalent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subject_equivalent (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, numero_ordre INT DEFAULT NULL, code VARCHAR(50) NOT NULL, libelle VARCHAR(150) NOT NULL, subject_paren VARCHAR(100) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_F8297C09C32A47EE (school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subject_type (id INT AUTO_INCREMENT NOT NULL, order_number INT NOT NULL, label VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teacher (id INT AUTO_INCREMENT NOT NULL, employee_id INT NOT NULL, specialization VARCHAR(255) DEFAULT NULL, education LONGTEXT DEFAULT NULL, experience LONGTEXT DEFAULT NULL, certification VARCHAR(255) DEFAULT NULL, teaching_hours NUMERIC(5, 2) DEFAULT NULL, is_class_teacher TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_B0F6A6D58C03F15C (employee_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teacher_subject (teacher_id INT NOT NULL, subject_id INT NOT NULL, INDEX IDX_360CB33B41807E1D (teacher_id), INDEX IDX_360CB33B23EDC87 (subject_id), PRIMARY KEY(teacher_id, subject_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teacher_level (teacher_id INT NOT NULL, level_id INT NOT NULL, INDEX IDX_CB15704E41807E1D (teacher_id), INDEX IDX_CB15704E5FB14BA7 (level_id), PRIMARY KEY(teacher_id, level_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE time_slot (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, name VARCHAR(100) NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL, type VARCHAR(20) NOT NULL, order_number INT NOT NULL, color VARCHAR(50) DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_1B3294AC32A47EE (school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, school_group_id INT DEFAULT NULL, last_school_id INT DEFAULT NULL, username VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL, must_change_password TINYINT(1) NOT NULL, last_login DATETIME DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, address LONGTEXT DEFAULT NULL, date_of_birth DATE DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, user_type VARCHAR(50) DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), INDEX IDX_8D93D64912ED03 (school_group_id), INDEX IDX_8D93D649D4E598E8 (last_school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_school (user_id INT NOT NULL, school_id INT NOT NULL, INDEX IDX_9CCCC186A76ED395 (user_id), INDEX IDX_9CCCC186C32A47EE (school_id), PRIMARY KEY(user_id, school_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_teaching_subject (user_id INT NOT NULL, subject_id INT NOT NULL, INDEX IDX_51E4BF3AA76ED395 (user_id), INDEX IDX_51E4BF3A23EDC87 (subject_id), PRIMARY KEY(user_id, subject_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C9CB944F1A FOREIGN KEY (student_id) REFERENCES student (id)');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C9CCAA91B FOREIGN KEY (absence_type_id) REFERENCES absence_type (id)');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C9D05A957B FOREIGN KEY (recorded_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C9CD130C9C FOREIGN KEY (justified_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C9C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C9EC8B7ADE FOREIGN KEY (period_id) REFERENCES period (id)');
        $this->addSql('ALTER TABLE absence_type ADD CONSTRAINT FK_FBCF99B6C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE bulletin ADD CONSTRAINT FK_2B7D89425FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id)');
        $this->addSql('ALTER TABLE bulletin ADD CONSTRAINT FK_2B7D8942EC8B7ADE FOREIGN KEY (period_id) REFERENCES period (id)');
        $this->addSql('ALTER TABLE bulletin ADD CONSTRAINT FK_2B7D8942C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE bulletin ADD CONSTRAINT FK_2B7D8942D2EECC3F FOREIGN KEY (school_year_id) REFERENCES school_year (id)');
        $this->addSql('ALTER TABLE bulletin ADD CONSTRAINT FK_2B7D8942B03A8386 FOREIGN KEY (created_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE bulletin ADD CONSTRAINT FK_2B7D8942C69DE5E5 FOREIGN KEY (validated_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE bulletin_line ADD CONSTRAINT FK_140A301FD1AAB236 FOREIGN KEY (bulletin_id) REFERENCES bulletin (id)');
        $this->addSql('ALTER TABLE bulletin_line ADD CONSTRAINT FK_140A301FCB944F1A FOREIGN KEY (student_id) REFERENCES student (id)');
        $this->addSql('ALTER TABLE cash_deposit ADD CONSTRAINT FK_CB378F65A917CC69 FOREIGN KEY (cash_register_id) REFERENCES cash_register (id)');
        $this->addSql('ALTER TABLE cash_deposit ADD CONSTRAINT FK_CB378F65D05A957B FOREIGN KEY (recorded_by_id) REFERENCES `user` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE cash_deposit ADD CONSTRAINT FK_CB378F652D234F6A FOREIGN KEY (approved_by_id) REFERENCES `user` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE cash_register ADD CONSTRAINT FK_3D7AB1D9C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE cash_register ADD CONSTRAINT FK_3D7AB1D92EDB0489 FOREIGN KEY (cashier_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE cash_register ADD CONSTRAINT FK_3D7AB1D9C69DE5E5 FOREIGN KEY (validated_by_id) REFERENCES `user` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE cash_register ADD CONSTRAINT FK_3D7AB1D92B62D3A1 FOREIGN KEY (authorized_by_id) REFERENCES `user` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE classroom ADD CONSTRAINT FK_497D309DC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE classroom ADD CONSTRAINT FK_497D309DD2EECC3F FOREIGN KEY (school_year_id) REFERENCES school_year (id)');
        $this->addSql('ALTER TABLE classroom ADD CONSTRAINT FK_497D309D5FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id)');
        $this->addSql('ALTER TABLE classroom ADD CONSTRAINT FK_497D309D680CAB68 FOREIGN KEY (faculty_id) REFERENCES faculty (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE classroom ADD CONSTRAINT FK_497D309DA6005CA0 FOREIGN KEY (round_id) REFERENCES round (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE classroom ADD CONSTRAINT FK_497D309D79780A7E FOREIGN KEY (main_teacher_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE classroom ADD CONSTRAINT FK_497D309D54177093 FOREIGN KEY (room_id) REFERENCES room (id)');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F28598C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB96278D5A8 FOREIGN KEY (classroom_id) REFERENCES classroom (id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB923EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB941807E1D FOREIGN KEY (teacher_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB9D62B0FA FOREIGN KEY (time_slot_id) REFERENCES time_slot (id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB954177093 FOREIGN KEY (room_id) REFERENCES room (id)');
        $this->addSql('ALTER TABLE cycle ADD CONSTRAINT FK_B086D193C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE depense ADD CONSTRAINT FK_34059757A917CC69 FOREIGN KEY (cash_register_id) REFERENCES cash_register (id)');
        $this->addSql('ALTER TABLE depense ADD CONSTRAINT FK_34059757C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE depense ADD CONSTRAINT FK_34059757D05A957B FOREIGN KEY (recorded_by_id) REFERENCES `user` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A1A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE employee_school ADD CONSTRAINT FK_D0AF1E2E8C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE employee_school ADD CONSTRAINT FK_D0AF1E2EC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A5756278D5A8 FOREIGN KEY (classroom_id) REFERENCES classroom (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A57523EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575EC8B7ADE FOREIGN KEY (period_id) REFERENCES period (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A57541807E1D FOREIGN KEY (teacher_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE faculty ADD CONSTRAINT FK_179660435EC1162 FOREIGN KEY (cycle_id) REFERENCES cycle (id)');
        $this->addSql('ALTER TABLE faculty ADD CONSTRAINT FK_17966043C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE fee ADD CONSTRAINT FK_964964B5C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE fee ADD CONSTRAINT FK_964964B55FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id)');
        $this->addSql('ALTER TABLE fee_schedule ADD CONSTRAINT FK_3806BAFCAB45AECA FOREIGN KEY (fee_id) REFERENCES fee (id)');
        $this->addSql('ALTER TABLE `grade` ADD CONSTRAINT FK_595AAE34456C5646 FOREIGN KEY (evaluation_id) REFERENCES evaluation (id)');
        $this->addSql('ALTER TABLE `grade` ADD CONSTRAINT FK_595AAE34CB944F1A FOREIGN KEY (student_id) REFERENCES student (id)');
        $this->addSql('ALTER TABLE `grade` ADD CONSTRAINT FK_595AAE34C443EDD FOREIGN KEY (entered_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC13C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC135EC1162 FOREIGN KEY (cycle_id) REFERENCES cycle (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE mobile_money_config ADD CONSTRAINT FK_5A7666C9C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAE92F8F78 FOREIGN KEY (recipient_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DCB944F1A FOREIGN KEY (student_id) REFERENCES student (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DAB45AECA FOREIGN KEY (fee_id) REFERENCES fee (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D2573764A FOREIGN KEY (student_fee_id) REFERENCES student_fee (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DD05A957B FOREIGN KEY (recorded_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DA917CC69 FOREIGN KEY (cash_register_id) REFERENCES cash_register (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE period ADD CONSTRAINT FK_C5B81ECEC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE period ADD CONSTRAINT FK_C5B81ECED2EECC3F FOREIGN KEY (school_year_id) REFERENCES school_year (id)');
        $this->addSql('ALTER TABLE pre_registration ADD CONSTRAINT FK_A2FEF1B9C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE pre_registration ADD CONSTRAINT FK_A2FEF1B92EC20237 FOREIGN KEY (requested_level_id) REFERENCES level (id)');
        $this->addSql('ALTER TABLE pre_registration ADD CONSTRAINT FK_A2FEF1B9D2EECC3F FOREIGN KEY (school_year_id) REFERENCES school_year (id)');
        $this->addSql('ALTER TABLE pre_registration ADD CONSTRAINT FK_A2FEF1B9C69DE5E5 FOREIGN KEY (validated_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE pre_registration ADD CONSTRAINT FK_A2FEF1B979F7D87D FOREIGN KEY (submitted_by_id) REFERENCES `user` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pre_registration ADD CONSTRAINT FK_A2FEF1B970E6A2D4 FOREIGN KEY (existing_student_id) REFERENCES student (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pre_registration_document ADD CONSTRAINT FK_413A5C65FB6C0FEA FOREIGN KEY (pre_registration_id) REFERENCES pre_registration (id)');
        $this->addSql('ALTER TABLE pre_registration_document ADD CONSTRAINT FK_413A5C6561232A4F FOREIGN KEY (document_type_id) REFERENCES document_type (id)');
        $this->addSql('ALTER TABLE pre_registration_document ADD CONSTRAINT FK_413A5C65C69DE5E5 FOREIGN KEY (validated_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE registration ADD CONSTRAINT FK_62A8A7A7C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE registration ADD CONSTRAINT FK_62A8A7A7D2EECC3F FOREIGN KEY (school_year_id) REFERENCES school_year (id)');
        $this->addSql('ALTER TABLE registration ADD CONSTRAINT FK_62A8A7A76278D5A8 FOREIGN KEY (classroom_id) REFERENCES classroom (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE registration ADD CONSTRAINT FK_62A8A7A7FB6C0FEA FOREIGN KEY (pre_registration_id) REFERENCES pre_registration (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519BC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE round ADD CONSTRAINT FK_C5EEEA345EC1162 FOREIGN KEY (cycle_id) REFERENCES cycle (id)');
        $this->addSql('ALTER TABLE round ADD CONSTRAINT FK_C5EEEA34C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABB12ED03 FOREIGN KEY (school_group_id) REFERENCES school_group (id)');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33D526A7D3 FOREIGN KEY (parent_user_id) REFERENCES `user` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33FB6C0FEA FOREIGN KEY (pre_registration_id) REFERENCES pre_registration (id)');
        $this->addSql('ALTER TABLE student_dropout ADD CONSTRAINT FK_7FBF5A31CB944F1A FOREIGN KEY (student_id) REFERENCES student (id)');
        $this->addSql('ALTER TABLE student_dropout ADD CONSTRAINT FK_7FBF5A31D05A957B FOREIGN KEY (recorded_by_id) REFERENCES `user` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE student_dropout ADD CONSTRAINT FK_7FBF5A31C69DE5E5 FOREIGN KEY (validated_by_id) REFERENCES `user` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE student_fee ADD CONSTRAINT FK_346113CB944F1A FOREIGN KEY (student_id) REFERENCES student (id)');
        $this->addSql('ALTER TABLE student_fee ADD CONSTRAINT FK_346113AB45AECA FOREIGN KEY (fee_id) REFERENCES fee (id)');
        $this->addSql('ALTER TABLE student_fee ADD CONSTRAINT FK_346113833D8F43 FOREIGN KEY (registration_id) REFERENCES registration (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE student_transfer ADD CONSTRAINT FK_F3BFEF5BCB944F1A FOREIGN KEY (student_id) REFERENCES student (id)');
        $this->addSql('ALTER TABLE student_transfer ADD CONSTRAINT FK_F3BFEF5B5F3E0F4E FOREIGN KEY (from_classroom_id) REFERENCES classroom (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE student_transfer ADD CONSTRAINT FK_F3BFEF5BB6ED7674 FOREIGN KEY (to_classroom_id) REFERENCES classroom (id)');
        $this->addSql('ALTER TABLE student_transfer ADD CONSTRAINT FK_F3BFEF5BD2EECC3F FOREIGN KEY (school_year_id) REFERENCES school_year (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE student_transfer ADD CONSTRAINT FK_F3BFEF5BD05A957B FOREIGN KEY (recorded_by_id) REFERENCES `user` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE subject ADD CONSTRAINT FK_FBCE3E7AC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE subject ADD CONSTRAINT FK_FBCE3E7A5FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id)');
        $this->addSql('ALTER TABLE subject ADD CONSTRAINT FK_FBCE3E7AC54C8C93 FOREIGN KEY (type_id) REFERENCES subject_type (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE subject ADD CONSTRAINT FK_FBCE3E7AA8A850D1 FOREIGN KEY (subject_equivalent_id) REFERENCES subject_equivalent (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE subject_equivalent ADD CONSTRAINT FK_F8297C09C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE teacher ADD CONSTRAINT FK_B0F6A6D58C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id)');
        $this->addSql('ALTER TABLE teacher_subject ADD CONSTRAINT FK_360CB33B41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE teacher_subject ADD CONSTRAINT FK_360CB33B23EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id)');
        $this->addSql('ALTER TABLE teacher_level ADD CONSTRAINT FK_CB15704E41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE teacher_level ADD CONSTRAINT FK_CB15704E5FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id)');
        $this->addSql('ALTER TABLE time_slot ADD CONSTRAINT FK_1B3294AC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D64912ED03 FOREIGN KEY (school_group_id) REFERENCES school_group (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D649D4E598E8 FOREIGN KEY (last_school_id) REFERENCES school (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_school ADD CONSTRAINT FK_9CCCC186A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE user_school ADD CONSTRAINT FK_9CCCC186C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE user_teaching_subject ADD CONSTRAINT FK_51E4BF3AA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE user_teaching_subject ADD CONSTRAINT FK_51E4BF3A23EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C9CB944F1A');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C9CCAA91B');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C9D05A957B');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C9CD130C9C');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C9C32A47EE');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C9EC8B7ADE');
        $this->addSql('ALTER TABLE absence_type DROP FOREIGN KEY FK_FBCF99B6C32A47EE');
        $this->addSql('ALTER TABLE bulletin DROP FOREIGN KEY FK_2B7D89425FB14BA7');
        $this->addSql('ALTER TABLE bulletin DROP FOREIGN KEY FK_2B7D8942EC8B7ADE');
        $this->addSql('ALTER TABLE bulletin DROP FOREIGN KEY FK_2B7D8942C32A47EE');
        $this->addSql('ALTER TABLE bulletin DROP FOREIGN KEY FK_2B7D8942D2EECC3F');
        $this->addSql('ALTER TABLE bulletin DROP FOREIGN KEY FK_2B7D8942B03A8386');
        $this->addSql('ALTER TABLE bulletin DROP FOREIGN KEY FK_2B7D8942C69DE5E5');
        $this->addSql('ALTER TABLE bulletin_line DROP FOREIGN KEY FK_140A301FD1AAB236');
        $this->addSql('ALTER TABLE bulletin_line DROP FOREIGN KEY FK_140A301FCB944F1A');
        $this->addSql('ALTER TABLE cash_deposit DROP FOREIGN KEY FK_CB378F65A917CC69');
        $this->addSql('ALTER TABLE cash_deposit DROP FOREIGN KEY FK_CB378F65D05A957B');
        $this->addSql('ALTER TABLE cash_deposit DROP FOREIGN KEY FK_CB378F652D234F6A');
        $this->addSql('ALTER TABLE cash_register DROP FOREIGN KEY FK_3D7AB1D9C32A47EE');
        $this->addSql('ALTER TABLE cash_register DROP FOREIGN KEY FK_3D7AB1D92EDB0489');
        $this->addSql('ALTER TABLE cash_register DROP FOREIGN KEY FK_3D7AB1D9C69DE5E5');
        $this->addSql('ALTER TABLE cash_register DROP FOREIGN KEY FK_3D7AB1D92B62D3A1');
        $this->addSql('ALTER TABLE classroom DROP FOREIGN KEY FK_497D309DC32A47EE');
        $this->addSql('ALTER TABLE classroom DROP FOREIGN KEY FK_497D309DD2EECC3F');
        $this->addSql('ALTER TABLE classroom DROP FOREIGN KEY FK_497D309D5FB14BA7');
        $this->addSql('ALTER TABLE classroom DROP FOREIGN KEY FK_497D309D680CAB68');
        $this->addSql('ALTER TABLE classroom DROP FOREIGN KEY FK_497D309DA6005CA0');
        $this->addSql('ALTER TABLE classroom DROP FOREIGN KEY FK_497D309D79780A7E');
        $this->addSql('ALTER TABLE classroom DROP FOREIGN KEY FK_497D309D54177093');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY FK_E98F28598C03F15C');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB96278D5A8');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB923EDC87');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB941807E1D');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB9D62B0FA');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB954177093');
        $this->addSql('ALTER TABLE cycle DROP FOREIGN KEY FK_B086D193C32A47EE');
        $this->addSql('ALTER TABLE depense DROP FOREIGN KEY FK_34059757A917CC69');
        $this->addSql('ALTER TABLE depense DROP FOREIGN KEY FK_34059757C32A47EE');
        $this->addSql('ALTER TABLE depense DROP FOREIGN KEY FK_34059757D05A957B');
        $this->addSql('ALTER TABLE employee DROP FOREIGN KEY FK_5D9F75A1A76ED395');
        $this->addSql('ALTER TABLE employee_school DROP FOREIGN KEY FK_D0AF1E2E8C03F15C');
        $this->addSql('ALTER TABLE employee_school DROP FOREIGN KEY FK_D0AF1E2EC32A47EE');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A5756278D5A8');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A57523EDC87');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A575EC8B7ADE');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A57541807E1D');
        $this->addSql('ALTER TABLE faculty DROP FOREIGN KEY FK_179660435EC1162');
        $this->addSql('ALTER TABLE faculty DROP FOREIGN KEY FK_17966043C32A47EE');
        $this->addSql('ALTER TABLE fee DROP FOREIGN KEY FK_964964B5C32A47EE');
        $this->addSql('ALTER TABLE fee DROP FOREIGN KEY FK_964964B55FB14BA7');
        $this->addSql('ALTER TABLE fee_schedule DROP FOREIGN KEY FK_3806BAFCAB45AECA');
        $this->addSql('ALTER TABLE `grade` DROP FOREIGN KEY FK_595AAE34456C5646');
        $this->addSql('ALTER TABLE `grade` DROP FOREIGN KEY FK_595AAE34CB944F1A');
        $this->addSql('ALTER TABLE `grade` DROP FOREIGN KEY FK_595AAE34C443EDD');
        $this->addSql('ALTER TABLE level DROP FOREIGN KEY FK_9AEACC13C32A47EE');
        $this->addSql('ALTER TABLE level DROP FOREIGN KEY FK_9AEACC135EC1162');
        $this->addSql('ALTER TABLE mobile_money_config DROP FOREIGN KEY FK_5A7666C9C32A47EE');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAE92F8F78');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840DCB944F1A');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840DAB45AECA');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D2573764A');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840DD05A957B');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840DA917CC69');
        $this->addSql('ALTER TABLE period DROP FOREIGN KEY FK_C5B81ECEC32A47EE');
        $this->addSql('ALTER TABLE period DROP FOREIGN KEY FK_C5B81ECED2EECC3F');
        $this->addSql('ALTER TABLE pre_registration DROP FOREIGN KEY FK_A2FEF1B9C32A47EE');
        $this->addSql('ALTER TABLE pre_registration DROP FOREIGN KEY FK_A2FEF1B92EC20237');
        $this->addSql('ALTER TABLE pre_registration DROP FOREIGN KEY FK_A2FEF1B9D2EECC3F');
        $this->addSql('ALTER TABLE pre_registration DROP FOREIGN KEY FK_A2FEF1B9C69DE5E5');
        $this->addSql('ALTER TABLE pre_registration DROP FOREIGN KEY FK_A2FEF1B979F7D87D');
        $this->addSql('ALTER TABLE pre_registration DROP FOREIGN KEY FK_A2FEF1B970E6A2D4');
        $this->addSql('ALTER TABLE pre_registration_document DROP FOREIGN KEY FK_413A5C65FB6C0FEA');
        $this->addSql('ALTER TABLE pre_registration_document DROP FOREIGN KEY FK_413A5C6561232A4F');
        $this->addSql('ALTER TABLE pre_registration_document DROP FOREIGN KEY FK_413A5C65C69DE5E5');
        $this->addSql('ALTER TABLE registration DROP FOREIGN KEY FK_62A8A7A7C32A47EE');
        $this->addSql('ALTER TABLE registration DROP FOREIGN KEY FK_62A8A7A7D2EECC3F');
        $this->addSql('ALTER TABLE registration DROP FOREIGN KEY FK_62A8A7A76278D5A8');
        $this->addSql('ALTER TABLE registration DROP FOREIGN KEY FK_62A8A7A7FB6C0FEA');
        $this->addSql('ALTER TABLE room DROP FOREIGN KEY FK_729F519BC32A47EE');
        $this->addSql('ALTER TABLE round DROP FOREIGN KEY FK_C5EEEA345EC1162');
        $this->addSql('ALTER TABLE round DROP FOREIGN KEY FK_C5EEEA34C32A47EE');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABB12ED03');
        $this->addSql('ALTER TABLE student DROP FOREIGN KEY FK_B723AF33C32A47EE');
        $this->addSql('ALTER TABLE student DROP FOREIGN KEY FK_B723AF33D526A7D3');
        $this->addSql('ALTER TABLE student DROP FOREIGN KEY FK_B723AF33FB6C0FEA');
        $this->addSql('ALTER TABLE student_dropout DROP FOREIGN KEY FK_7FBF5A31CB944F1A');
        $this->addSql('ALTER TABLE student_dropout DROP FOREIGN KEY FK_7FBF5A31D05A957B');
        $this->addSql('ALTER TABLE student_dropout DROP FOREIGN KEY FK_7FBF5A31C69DE5E5');
        $this->addSql('ALTER TABLE student_fee DROP FOREIGN KEY FK_346113CB944F1A');
        $this->addSql('ALTER TABLE student_fee DROP FOREIGN KEY FK_346113AB45AECA');
        $this->addSql('ALTER TABLE student_fee DROP FOREIGN KEY FK_346113833D8F43');
        $this->addSql('ALTER TABLE student_transfer DROP FOREIGN KEY FK_F3BFEF5BCB944F1A');
        $this->addSql('ALTER TABLE student_transfer DROP FOREIGN KEY FK_F3BFEF5B5F3E0F4E');
        $this->addSql('ALTER TABLE student_transfer DROP FOREIGN KEY FK_F3BFEF5BB6ED7674');
        $this->addSql('ALTER TABLE student_transfer DROP FOREIGN KEY FK_F3BFEF5BD2EECC3F');
        $this->addSql('ALTER TABLE student_transfer DROP FOREIGN KEY FK_F3BFEF5BD05A957B');
        $this->addSql('ALTER TABLE subject DROP FOREIGN KEY FK_FBCE3E7AC32A47EE');
        $this->addSql('ALTER TABLE subject DROP FOREIGN KEY FK_FBCE3E7A5FB14BA7');
        $this->addSql('ALTER TABLE subject DROP FOREIGN KEY FK_FBCE3E7AC54C8C93');
        $this->addSql('ALTER TABLE subject DROP FOREIGN KEY FK_FBCE3E7AA8A850D1');
        $this->addSql('ALTER TABLE subject_equivalent DROP FOREIGN KEY FK_F8297C09C32A47EE');
        $this->addSql('ALTER TABLE teacher DROP FOREIGN KEY FK_B0F6A6D58C03F15C');
        $this->addSql('ALTER TABLE teacher_subject DROP FOREIGN KEY FK_360CB33B41807E1D');
        $this->addSql('ALTER TABLE teacher_subject DROP FOREIGN KEY FK_360CB33B23EDC87');
        $this->addSql('ALTER TABLE teacher_level DROP FOREIGN KEY FK_CB15704E41807E1D');
        $this->addSql('ALTER TABLE teacher_level DROP FOREIGN KEY FK_CB15704E5FB14BA7');
        $this->addSql('ALTER TABLE time_slot DROP FOREIGN KEY FK_1B3294AC32A47EE');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D64912ED03');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D649D4E598E8');
        $this->addSql('ALTER TABLE user_school DROP FOREIGN KEY FK_9CCCC186A76ED395');
        $this->addSql('ALTER TABLE user_school DROP FOREIGN KEY FK_9CCCC186C32A47EE');
        $this->addSql('ALTER TABLE user_teaching_subject DROP FOREIGN KEY FK_51E4BF3AA76ED395');
        $this->addSql('ALTER TABLE user_teaching_subject DROP FOREIGN KEY FK_51E4BF3A23EDC87');
        $this->addSql('DROP TABLE absence');
        $this->addSql('DROP TABLE absence_type');
        $this->addSql('DROP TABLE bulletin');
        $this->addSql('DROP TABLE bulletin_line');
        $this->addSql('DROP TABLE cash_deposit');
        $this->addSql('DROP TABLE cash_register');
        $this->addSql('DROP TABLE classroom');
        $this->addSql('DROP TABLE contract');
        $this->addSql('DROP TABLE course');
        $this->addSql('DROP TABLE cycle');
        $this->addSql('DROP TABLE depense');
        $this->addSql('DROP TABLE document_type');
        $this->addSql('DROP TABLE employee');
        $this->addSql('DROP TABLE employee_school');
        $this->addSql('DROP TABLE evaluation');
        $this->addSql('DROP TABLE faculty');
        $this->addSql('DROP TABLE fee');
        $this->addSql('DROP TABLE fee_schedule');
        $this->addSql('DROP TABLE `grade`');
        $this->addSql('DROP TABLE level');
        $this->addSql('DROP TABLE mobile_money_config');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE payment_webhook_event');
        $this->addSql('DROP TABLE period');
        $this->addSql('DROP TABLE pre_registration');
        $this->addSql('DROP TABLE pre_registration_document');
        $this->addSql('DROP TABLE registration');
        $this->addSql('DROP TABLE room');
        $this->addSql('DROP TABLE round');
        $this->addSql('DROP TABLE school');
        $this->addSql('DROP TABLE school_group');
        $this->addSql('DROP TABLE school_year');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE student_dropout');
        $this->addSql('DROP TABLE student_fee');
        $this->addSql('DROP TABLE student_transfer');
        $this->addSql('DROP TABLE subject');
        $this->addSql('DROP TABLE subject_equivalent');
        $this->addSql('DROP TABLE subject_type');
        $this->addSql('DROP TABLE teacher');
        $this->addSql('DROP TABLE teacher_subject');
        $this->addSql('DROP TABLE teacher_level');
        $this->addSql('DROP TABLE time_slot');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('DROP TABLE user_school');
        $this->addSql('DROP TABLE user_teaching_subject');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
